mySite/applications/myList/urls.py
from django.urls import path

from .views import (
    random_redirect,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
)


app_name = "myList"

urlpatterns = [
    path("", random_redirect, name="randomRedirect"),
    path("<str:model_name>/", ProductListView.as_view(), name="choose"),
    path("<str:model_name>/<slug:slug>", ProductDetailView.as_view(), name="detail"),
    path(
        "<str:model_name>/<slug:slug>/delete",
        ProductDeleteView.as_view(),
        name="delete",
    ),
]

mySite/mySite/urls.py
import debug_toolbar

from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),

    path('', RedirectView.as_view(pattern_name='microblog:list')),
    path('microblog/', include('microblog.urls', namespace='microblog')),
    path('about-me/', include('resume.urls')),
    path('myList/', include('myList.urls', namespace='myList')),
    path('rating/', include('rating.urls', namespace='rating')),
    path('api/v1/', include('api.urls', namespace='api')),
]


if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mySite/applications/myList/models.py
from itertools import groupby
from operator import attrgetter

from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse

from rating.models import RatingItem, Round


PRODUCT_TYPE = [
    ("film", "Фильм"),
    ("series", "Сериал"),
    ("anime", "Аниме"),
    ("game", "Игра"),
    ("book", "Книга"),
]

PRODUCT_STATUS = [
    ("pn", "Запланировано"),
    ("ga", "В процессе"),
    ("rv", "Повтор"),
    ("ac", "Завершено"),
    ("ab", "Брошено"),
    ("pp", "Отложено"),
]


class ProductQuerySet(models.QuerySet):
    def annotate_avg_p_rate(self):
        return self.order_by("status").annotate(
            avg_p_rate=Round(
                models.Avg(
                    "rating__score", filter=models.Q(rating__rating_purpose_type="P")
                )
            )
        )

    def separated_by_status(self):
        query = self.annotate_avg_p_rate()
        dict_ = {k: list(vs) for k, vs in groupby(query, attrgetter("status"))}
        return {status1: dict_.get(status0, []) for status0, status1 in PRODUCT_STATUS}


class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def annotate_avg_p_rate(self):
        return self.get_queryset().annotate_avg_p_rate()

    def separated_by_status(self):
        return self.get_queryset().separated_by_status()


class Product(models.Model):
    objects = ProductManager()
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    description = models.TextField(null=True, blank=True, verbose_name="Описание")
    opinion = models.TextField(null=True, blank=True, verbose_name="Мое мнение")
    slug = models.SlugField(max_length=160, null=True, verbose_name="Слаг")
    status = models.CharField(
        max_length=3,
        blank=False,
        null=False,
        choices=PRODUCT_STATUS,
        default="ac",
        verbose_name="Статус",
    )
    i_recommend = models.BooleanField(default=False, verbose_name="Рекомендую")
    url = models.URLField(null=True, blank=True, verbose_name="Ссылка")
    poster = models.ImageField(
        blank=True, null=True, upload_to="posters/%Y/%m/%d", verbose_name="Постер"
    )
    is_published = models.BooleanField(default=False, verbose_name="Опубликовано")

    def __str__(self, class_name_verbose, name) -> str:
        return f'{class_name_verbose} "{name}"'

    def __repr__(self, class_name, pk, name, status) -> str:
        return f"{class_name}({pk=}, {name=}, {status=})"

    def get_absolute_url(self):
        return reverse(
            "myList:detail",
            kwargs={"model_name": self.__class__.__name__.lower(), "slug": self.slug},
        )

    class Meta:
        abstract = True


class Film(Product):
    rating = GenericRelation(RatingItem, related_query_name="films")
    review_count = models.PositiveIntegerField(
        default=0,
        verbose_name="Число повторных просмотров",
    )

    def __str__(self) -> str:
        return super().__str__("Фильм", self.name)

    def __repr__(self) -> str:
        return super().__repr__("Film", self.pk, self.name, self.status)

    class Meta:
        verbose_name = "фильм"
        verbose_name_plural = "Фильмы"
        ordering = ["status"]


class Series(Product):
    rating = GenericRelation(RatingItem, related_query_name="series")
    review_count = models.PositiveIntegerField(
        default=0,
        verbose_name="Число повторных просмотров",
    )

    def __str__(self) -> str:
        return super().__str__("Сериал", self.name)

    def __repr__(self) -> str:
        return super().__repr__("Series", self.pk, self.name, self.status)

    class Meta:
        verbose_name = "Сериал"
        verbose_name_plural = "Сериалы"
        ordering = ["status"]


class Book(Product):
    rating = GenericRelation(RatingItem, related_query_name="books")
    ISBN = models.CharField(max_length=30, unique=True, verbose_name="Номер книги")

    def __str__(self) -> str:
        return super().__str__("Книга", self.name)

    def __repr__(self) -> str:
        return super().__repr__("Book", self.pk, self.name, self.status)

    class Meta:
        verbose_name = "Книга"
        verbose_name_plural = "Книги"
        ordering = ["status"]


class Anime(Product):
    rating = GenericRelation(RatingItem, related_query_name="anime")
    ANIME_TYPE = [
        ("Ov", "OVA"),
        ("Fi", "Фильм"),
        ("Se", "Сериал"),
        ("On", "ONA"),
        ("Sp", "Спешл"),
    ]

    anime_type = models.CharField(
        max_length=2, default="Se", choices=ANIME_TYPE, verbose_name="Тип аниме"
    )

    def __str__(self) -> str:
        return super().__str__("Аниме", self.name)

    def __repr__(self) -> str:
        return super().__repr__("Anime", self.pk, self.name, self.status)

    class Meta:
        verbose_name = "Аниме"
        verbose_name_plural = "Аниме"
        ordering = ["status"]


class Game(Product):
    rating = GenericRelation(RatingItem, related_query_name="games")

    def __str__(self) -> str:
        return super().__str__("Игра", self.name)

    def __repr__(self) -> str:
        return super().__repr__("Game", self.pk, self.name, self.status)

    class Meta:
        verbose_name = "Игра"
        verbose_name_plural = "Игры"
        ordering = ["status"]

mySite/applications/myList/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from .models import Anime, Book, Film, Game, Series


class CKAbstractAdminForm(forms.ModelForm):
    class Meta:
        fields = "__all__"
        widgets = {"description": CKEditorWidget, "opinion": CKEditorWidget}


class CKBookAdminForm(forms.ModelForm):
    class Meta(CKAbstractAdminForm.Meta):
        model = Book


class CKAnimeAdminForm(forms.ModelForm):
    class Meta(CKAbstractAdminForm.Meta):
        model = Anime


class CKFilmAdminForm(forms.ModelForm):
    class Meta(CKAbstractAdminForm.Meta):
        model = Film


class CKGameAdminForm(forms.ModelForm):
    class Meta(CKAbstractAdminForm.Meta):
        model = Game


class CKSeriesAdminForm(forms.ModelForm):
    class Meta(CKAbstractAdminForm.Meta):
        model = Series

mySite/applications/myList/views.py
from random import choice

from django.shortcuts import redirect, render
from django.views.generic.base import ContextMixin, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView

from .mixins import ModelNameDispatchMixin


def random_redirect(request):
    to = ("series/", "book/", "film/", "game/")
    return redirect(choice(to))


class ProductListView(ModelNameDispatchMixin, ContextMixin, View):
    template_name = "myList/myList.html"

    def get(self, request, *args, **kwargs):
        verbosed = {
            "film": "фильмов",
            "game": "игр",
            "series": "сериалов",
            "book": "книг",
            "anime": "аниме",
        }
        context = self.get_context_data(
            title=f"Список {verbosed[self.model._meta.model_name]}",
            dict_queryset=self.model.objects.separated_by_status(),
        )

        return render(request, self.template_name, context)


class ProductDetailView(ModelNameDispatchMixin, DetailView):
    context_object_name = "product"
    template_name = "myList/productDetail.html"
    slug_url_kwarg = "slug"

    def get_queryset(self):
        return self.model.objects.annotate_avg_p_rate()

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object, title=self.object.name)
        return self.render_to_response(context)


class ProductDeleteView(ModelNameDispatchMixin, DeleteView):
    template_name = "myList/productDelete.html"
    context_object_name = "product"
    success_url = "/myList/"

mySite/applications/myList/templates/myList/anime.html
{% extends 'base.html' %}

mySite/applications/myList/templates/myList/myList.html
{% extends 'base.html' %}
{% load static %}
{% load humanize_data %}


{% block navigate %}
  {{ block.super }}
    {% include 'myList/inc/listNav.html' %}
  {% block search %}{% endblock search %}
{% endblock navigate %}


{% block extrastyle %}
    <link
      rel="stylesheet"
      type='text/css'
      href="{% static 'other/tableRewrite.css' %}">
{% endblock extrastyle %}


{% block main %}
<div class="container">
    <div class='row mt-2'>
      {% if dict_queryset %}
        <div class="col-md-9">
            {% for status_title, q_set in dict_queryset.items %}
            {% if q_set %}
            <div class='tblDiv'>
                <h5 class="text-white">{{status_title}}</h5>
                <table class='table table-dark table-stripes'>
                    <thead>
                        <tr>
                          <th scope="col" class='text-center'>№&nbsp;</th>
                          <th scope="col">Название</th>
                          <th class='text-center' scope="col">&nbsp;Оценка&nbsp;</th>
                          <th class='text-center' scope="col">&nbsp;Советую?</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for q_set_ele in q_set %}
                      {% if q_set_ele.is_published or request.user.is_staff or request.user.is_superuser %}
                        <tr>
                          <th scope='row' class='text-center'>{{forloop.counter}}</th>
                          <td>
                            <a href="{% url 'myList:detail' q_set_ele|model_name q_set_ele.slug %}" class="hoveredReverse current no-underline">{{q_set_ele.name}}</a>
                          </td>
                          <td class='text-center'>{{q_set_ele.avg_p_rate}}</td>
                          <td class='text-center'>{% if q_set_ele.i_recommend %}Да{% else %}Нет{%endif%}</td>
                        </tr>
                      {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <div class="col-md-3">
            {% include 'myList/inc/dynamicFiltersAndSearch.html' %}
        </div>
      {% else %}
        <h1 class="mt-5 text-white text-center">К сожалению, тут пока нет ни одной записи :(</h1>
      {% endif %}
    </div>
</div>
{% endblock main %}


{% block extra_scripts %}
    <script src="{% static 'other/filterRecommend.js' %}"></script>
{% endblock extra_scripts %}

mySite/applications/myList/templates/myList/productDelete.html
{% extends 'base.html' %}
{% load humanize_data %}

{% block navigate %}{% endblock navigate %}


{% block main %}
<div class="container mt-5">
<div class="form-group mx-auto">
  <h2 class="text-center text-white mt-3">
    Вы собираетесь <span class="text-danger">удалить</span> пост "<i>{{product}}</i>"
  </h2>
  <p class="text-center text-muted">Вы уверены, что хотите это сделать?</p>
  <div class="form-group">
    <form
      method="post"
      class="d-flex flex-column align-items-center justify-content-center"
      >
      {% csrf_token %}
      <div class="row">
        <div class="col">
              <a href="{% url 'myList:detail' model_name=product|model_name slug=product.slug %}" class="nav-link text-white fs-4 hovered">Назад</a>
        </div>
        <div class="col">
          <button type="submit" class="btn btn-danger fs-4">Удалить</button>
        </div>
      </div>
    </form>
  </div>
</div>
    </div>
{% endblock main %}

mySite/applications/myList/templates/myList/productDetail.html
{% extends 'base.html' %}
{% load humanize_data %}
{% load static %}


{% block navigate %}{% endblock navigate %}


{% block main %}
<div class="container mt-2">

  {% if user.is_superuser %}
    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center fs-3 border">
        <li>
            <a href="{% url 'myList:choose' model_name=product|model_name %}" class="nav-link mx-1 text-white hovered">Назад</a>
        </li>
        <li>
            <a href="{% url 'myList:delete' model_name=product|model_name slug=product.slug %}" class="nav-link mx-1 text-white hovered">Удалить</a>
        </li>
        <li>
            <a href="{% url_to_edit_object product %}" class="nav-link mx-1 text-white hovered">Обновить</a>
        </li>
        <li>
            <a href="{% url 'admin:index' %}" class="nav-link mx-1 text-white hovered">Админка</a>
        </li>
    </ul>
  {% else %}
    <ul class="nav mb-2 fs-3">
        <li>
            <a href="{% url 'myList:choose' model_name=product|model_name %}" class="nav-link mx-1 text-white hovered">← Назад</a>
        </li>
    </ul>
  {% endif %}
    <div class="row text-white">
        <div class="mx-auto">
          <h1 class="text-white">{{ product.name }}</h1>
          <p class="current">{{ product|object_verbose_name }} {% if product.i_recommend %} <span class="text-white">/</span> &#10003; я рекомендую{% endif %}</p>
        </div>
        <div class="row pb-5">
          <div class="col-md-3">
            <img src="{% if product.poster %}{{product.poster.url}}{% else %}{% static 'dummy.png' %}{% endif %}" alt="" style="max-width: 100%; height: auto;" />
            {% if product.avg_p_rate %}
              <p class="text-center" style='margin-bottom: 0px;'><span style='color: gold; font-size: 32px;'>{{product.avg_p_rate|starred}}</span><span style='font-size: 32px;' class="text-muted">{{product.avg_p_rate|not_starred}}</span></p>
              <h5 class='text-center'>{{product.avg_p_rate|floatformat:"0" }}/10 ({{product.avg_p_rate|rating_verbose}})</h5>
              <a style="text-align: center; display: block;'" class='text-center text-muted' href="{% url 'rating:detail' model_name=product|model_name pk=product.pk %}">перейти к полной оценке</a>
            {% else %}
              <p class="text-center text-muted" style='font-size: 32px; margin-bottom: 0px;'>★★★★★★★★★★</p>
              <h5 class="text-center">оценки нет</h5>
            {% endif %}
          </div>
          <div class="col-md-9">
            <h5 class="mt-2">Описание:</h5>
            <p class='mt-1' align='justify'>{{ product.description|safe }}</p>
            <h5 class="mt-2">Мое мнение:</h5>
            <p class="mt-1" align='justify'>{{product.opinion|safe}}</p>
          </div>
        </div>
    </div>
</div>
{% endblock main %}


{% block extra_scripts %}
<script>
  let colDiv = document.querySelector('.col-md-9')
  colDiv.querySelectorAll('p').forEach(e => e.className += ' text-muted'); 
</script>
{% endblock extra_scripts %}

mySite/applications/myList/templates/myList/ratingSystem.html
{% extends 'base.html' %}


{% block title %}Рейтинговая система{% endblock title %}


{% block navigate %}{% endblock navigate %}


{% block main %}
  <div class="container mt-2">
  <ul class="nav mb-2 fs-3">
    <li>
      <a href="{% url 'myList/randomRedirect' %}" class="nav-link mx-1 text-white hovered">← Назад</a>
    </li>
  </ul>
    <h3 class='text-white'>Введение:</h3>
    <p style='text-align:justify; font-size: 18px;' class="text-muted">Данная страница предназначена для того, чтобы объяснить рядовому пользователю то, какой системой оценивания я пользуюсь для просмотренных/прочтенных/проигранных произведений. Непосресредственно сама система не представляет из себя ничего интересного или уникального, но данное пояснение все же необходимо для полного понимания. Люди бывают разные, с разными подходами к оцениванию, и если они приходят ко мне на сайт, то я обязан разъяснить для них свой.</p>
    <h3 class='text-white'>Критерии:</h3>
    <p style='text-align:justify; font-size: 18px;' class="text-muted">Непосредственно сами критерии представляют собой мои маняфантазии. Произведения я стараюсь оценивать с позиции своих вкусов одновременно с попыткой в объективное оценивание, разделяя эти понятия, отчего для каждой оценки имеется свой нефиксированный набор критериев. В случае с моими вкусами тут все просто: критерий один - мое общее впечатление от произведения, в котором я описываю те аспекты, которые понравились лично мне. С объективным оцениванием все сложнее. Здесь для каждого типа произведения, будь то мультфильм, просто фильм, сериал, книга, игра, имеется свой набор уникальных критериев: проблематично оценивать раскадровку у игры или геймдизайн у книги. Иногда некоторые критерии могут быть пропущены по самым разным причинам.</p>
    <h3 class="text-white">Из чего складывается общая оценка:</h3>
    <p style='text-align:justify; font-size: 18px;' class="text-muted">Пока что только из среднего значения всех оценок одного типа (объективные или субъективные). Достаточно просто, но я пока разбираюсь с SQL, поэтому сложные агрегирующие запросы делать не умею. Дополнением к итоговой оценке идет сдвиг по принципу академической щедрости. В данный принцип я вкладываю немного другое значение, чем оно имеет (справка: "академическая щедрость" - принцип, при котором дебатирующие стороны при интерпретации слов оппонента не пытаются их негативно интерпретировать, дают ему фору для объяснения, не прибегают к софистике, додумывают слова для наиболее выигрышной позиции оппонента. Обобщу: ведут себя благосклонно по отношении к собеседнику ), а именно добавление к итоговой оценке определенное количество баллов в силу того, что либо само произведение, либо индустрия, в которой оно было произведено (кинопроизводство отдельной страны и т.д.) перспективно или очень интересно для меня. <b>Данный принцип распространяется только на мое субъективное мнение.</b></p>
    <h3 class="text-white">У меня лапки:</h3>
    <p style='text-align:justify; font-size: 18px;' class="text-muted">Тут мне стоит сказать еще раз, что я не претендую на истину в последней инстанции. Я могу ошибаться, а могу нарочно что-то недорассказать, чтобы моя позиция смотрелась гораздо выигрышнее. Полностью доверять моим оценкам себе дороже. Думайте своей головой.</p>
    <h3 class="text-white">Что бы я улучшил в своей системе:</h3>
    <p style='text-align:justify; font-size: 18px;' class="text-muted">На самом деле, пока что кроме какой-нибудь системы весов для оценок (вес - некоторое число, показывающая важность оценки, за которой оно закреплено. Пример: устанавливая вес атрибута сюжет в 0.5 я говорю о том, что если я поставлю сюжету произведения оценку 10, тогда к итоговой оценке прибавится 5 баллов (10*0.5=5)) мне добавить нечего, да и усложнять систему плохо со всех сторон.</p>
    <p style='text-align:justify; font-size: 18px;' class="text-muted">З.ы. эта часть текста может быть удалена, если я все-таки добавлю те вещи, о которых говорилось выше.</p>
  </div>
{% endblock main %}