mySite/applications/myList/urls.py
from django.urls import path

from .views import (
    random_redirect,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
)


app_name = "myList"

urlpatterns = [
    path("", random_redirect, name="randomRedirect"),
    path("<str:model_name>/", ProductListView.as_view(), name="choose"),
    path("<str:model_name>/<slug:slug>", ProductDetailView.as_view(), name="detail"),
    path(
        "<str:model_name>/<slug:slug>/delete",
        ProductDeleteView.as_view(),
        name="delete",
    ),
]

mySite/mySite/urls.py
import debug_toolbar

from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),

    path('', RedirectView.as_view(pattern_name='microblog:list')),
    path('microblog/', include('microblog.urls', namespace='microblog')),
    path('about-me/', include('resume.urls')),
    path('myList/', include('myList.urls', namespace='myList')),
    path('rating/', include('rating.urls', namespace='rating')),
    path('api/v1/', include('api.urls', namespace='api')),
]


if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mySite/templates/inc/_footer.html
<div class="container">
    <footer class="py-5 my-5 text-white border-top">
        <div class="row row-cols-5">
            <div class="col"></div>
            <div class="col">
              <h5>Написать мне</h5>
              <ul class="nav flex-column">
                <li class="nav-item mb-2"><a href="https://vk.com/dimalunev" class="nav-link p-0 text-muted">Вконтакте</a></li>
                <li class="nav-item mb-2"><a href="https://www.linkedin.com/in/dmitriy-lunev/" class="nav-link p-0 text-muted">LinkedIn</a></li>
                <li class="nav-item mb-2"><a href="mailto:dima.lunev14@gmail.com" class="nav-link p-0 text-muted">Почта</a></li>
                <li class="nav-item mb-2"><a href="https://t.me/alittlemoron" class="nav-link p-0 text-muted">Телеграм</a></li>
              </ul>
            </div>
            <div class="col">
              <h5>Серверы/игры/Списки</h5>
              <ul class="nav flex-column">
                <li class="nav-item mb-2"><a href="https://steamcommunity.com/id/Dmitriylunev/" class="nav-link p-0 text-muted">Steam</a></li>
                <li class="nav-item mb-2"><a href="https://shikimori.one/A+Little+Moron" class="nav-link p-0 text-muted">Shikimori</a></li>
                <li class="nav-item mb-2"><a href="https://www.kinopoisk.ru/user/15668721/" class="nav-link p-0 text-muted">Кинопоиск</a></li>
              </ul>
            </div>
            <div class="col">
              <h5>Разное</h5>
              <ul class="nav flex-column">
                <li class="nav-item mb-2"><a href="https://github.com/ALittleMoron/django-my-site" class="nav-link p-0 text-muted">Исходный код</a></li>
                <li class="nav-item mb-2"><a href="https://github.com/ALittleMoron/django-my-site/blob/main/mySite.todo" class="nav-link p-0 text-muted">Дорожная карта</a></li>
                <li class="nav-item mb-2"><a href="https://github.com/ALittleMoron/" class="nav-link p-0 text-muted">Мой GitHub</a></li>
                <li class="nav-item mb-2"><a href="{% url 'rating:ratingSystem' %}" class="nav-link p-0 text-muted">Рейтинговая система</a></li>
              </ul>
            </div>
            <div class="col">
            </div>
        </div>
            <div class="row mt-5">
                <p class="text-center text-muted">Проект распространяется по лицензии <a class="text-muted" href="https://unlicense.org">"The Unlicense"</a>.</p>
            </div>
      </footer>
</div>

mySite/templates/inc/_navbar.html
{% with url_name=request.path %}
    <div class="align-items-center justify-content-center justify-content-lg-start ">
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'microblog:list' %}" class="nav-link px-2 text-white hovered {% if 'microblog' in url_name %}current{% endif %}">Микроблог</a></li> .
        <li><a href="{% url 'aboutMe' %}" class="nav-link px-2 text-white hovered {% if 'about-me' in request.path %}current{% endif %}">Обо мне</a></li> .
        <li><a href="{% url 'myList:randomRedirect' %}" class="nav-link px-2 text-white hovered {% if 'myList' in url_name %}current{% endif %}">Библиотека</a></li>
        {% if user.is_superuser %}
        . <li><a href="{% url 'admin:index' %}" class="nav-link px-2 text-white hovered">Админка</a></li>
        {% endif %}
      </ul>

      {% block search %}
      {% endblock search %}
    </div>
{% endwith %}

mySite/templates/inc/_pagination.html
    {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation example" style='margin-top: 20px; display: flex; justify-content: center;'>
      <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
        {% else %}
            <li class="page-item disabled" >
              <a class="page-link" href="#" aria-label="Previous" aria-disabled="true">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
        {% endif %}

        {% for page in page_obj.paginator.page_range %}
          {% if page_obj.number == page %}
            <li class="page-item active" arial-current="page"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
          {% elif page > page_obj.number|add:-4 and page < page_obj.number|add:4 %}
            <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Previous">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
        {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" aria-label="Previous" aria-disabled="true">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}