mySite/applications/rating/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import ProductRatingView, RatingSystemView


app_name = "rating"

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="rating:ratingSystem"), name="homePage"),
    path("rating-system", RatingSystemView.as_view(), name="ratingSystem"),
    path(
        "<str:model_name>/<int:pk>/",
        ProductRatingView.as_view(),
        name="detail",
    ),
]

mySite/mySite/urls.py
import debug_toolbar

from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),

    path('', RedirectView.as_view(pattern_name='microblog:list')),
    path('microblog/', include('microblog.urls', namespace='microblog')),
    path('about-me/', include('resume.urls')),
    path('myList/', include('myList.urls', namespace='myList')),
    path('rating/', include('rating.urls', namespace='rating')),
    path('api/v1/', include('api.urls', namespace='api')),
]


if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mySite/applications/rating/models.py
from itertools import groupby
from operator import attrgetter

from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models


RATING_CHOICES = [
    (0, "Не указан"),
    (1, "Хуже некуда"),
    (2, "Ужасно"),
    (3, "Очень плохо"),
    (4, "Плохо"),
    (5, "Более-менее"),
    (6, "Нормально"),
    (7, "Хорошо"),
    (8, "Очень хорошо"),
    (9, "Великолепно"),
    (10, "Шедевр"),
]

RATING_PURPOSE_TYPES = [
    ("O", "Беспристрастное мнение"),
    ("P", "Личное мнение")
]


class Round(models.Func):
    function = "ROUND"
    template = "%(function)s(%(expressions)s)"


class RatingItemQuerySet(models.QuerySet):
    def separated_by_purpose_type(self):
        query = self.order_by("rating_purpose_type")
        dict_ = {
            k: list(vs) for k, vs in groupby(query, attrgetter("rating_purpose_type"))
        }
        return {type1: dict_.get(type0, []) for type0, type1 in RATING_PURPOSE_TYPES}


class RatingItemManager(models.Manager):
    def get_queryset(self):
        return RatingItemQuerySet(self.model, using=self._db)

    def separated_by_purpose_type(self):
        return self.get_queryset().separated_by_purpose_type()


class RatingItem(models.Model):
    """Класс модели элемента рейтинговой системы для тайтлов библиотеки."""

    objects = RatingItemManager()
    label = models.CharField(max_length=100, verbose_name="Пометка")
    positive_offset = models.IntegerField(
        default=0,
        verbose_name="сдвиг оценки",
        validators=[MinValueValidator(0), MaxValueValidator(4)],
    )
    rating_purpose_type = models.CharField(
        max_length=1,
        default="O",
        choices=RATING_PURPOSE_TYPES,
        verbose_name="Направленность элемента рейтинга",
    )
    explanation = models.TextField(
        null=True,
        blank=True,
        verbose_name="Объяснение",
    )
    score = models.IntegerField(
        default=0,
        choices=RATING_CHOICES,
        verbose_name="Оценка",
    )
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    # FIXME: переделать под особенности ContentType
    # @property
    # def avarage_rating_score(self) -> dict[str, float]:
    #     return RatingItem.objects.filter(parent=self).aggregate(
    #         o_avg=Round(models.Avg('score', filter=models.Q(rating_purpose_type='O'))),
    #         p_avg=Round(models.Avg('score', filter=models.Q(rating_purpose_type='P')))
    #     )

    def __str__(self) -> str:
        return (
            f'рейтинг для "{self.content_object if self.content_object else "пусоты"}"'
        )

    def __repr__(self) -> str:
        return f"RatingItem({self.pk=}, {self.label=}, {self.score=})"

    class Meta:
        verbose_name = "Элемент рейтинга"
        verbose_name_plural = "Элементы рейтинга"
        ordering = ["-label"]

mySite/applications/rating/views.py
from django.shortcuts import render
from django.views.generic.base import View

from myList.mixins import ModelNameDispatchMixin
from .models import RatingItem


class RatingSystemView(View):
    template_name = "rating/ratingSystem.html"
    http_method_names = ["get"]

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class ProductRatingView(ModelNameDispatchMixin, View):
    http_method_names = ["get"]
    template_name = "rating/productDetailRating.html"

    def get(self, request, *args, **kwargs):
        self.objects = RatingItem.objects.filter(
            object_id=self.kwargs.get("pk")
        ).separated_by_purpose_type()
        context = {
            "dict_queryset": self.objects,
            "goback_model": self.model._meta.model_name,
            "goback_slug": self.model.objects.get(pk=self.kwargs.get("pk")).slug,
        }
        return render(request, self.template_name, context)

mySite/applications/rating/templates/rating/productDetailRating.html
{% extends 'base.html' %}
{% load humanize_data %}
{% load static %}


{% block navigate %}{% endblock navigate %}

{% block main %}
  <div class="container mt-2">
  <ul class="nav mb-2 fs-3">
    <li>
      <a href="{% url 'myList:detail' model_name=goback_model slug=goback_slug %}" class="nav-link mx-1 text-white hovered">← Назад</a>
    </li>
  </ul>
    {% for purposeType, ratingItems in dict_queryset.items %}
    {% if ratingItems %}
    <h2 class="text-white text-center">{{purposeType}}:</h2>
      {% for ratingItem in ratingItems %}
        <div class='mx-5 mb-2'>
          <div class="row border">
             <div class="mt-1 col-md-4">
               <h5 class="text-white text-center">{{ratingItem.label}}:</h5>
             </div>
             <div class="mt-1 col-md-8">
                <p style='text-align: justify;' class="text-muted">{{ratingItem.explanation}}</p>
             </div>
              <p class="text-center" style='margin-bottom: 0px;'><span style='color: gold; font-size: 32px;'>{{ratingItem.score|starred}}</span><span style='font-size: 32px;' class="text-muted">{{ratingItem.score|not_starred}}</span></p>
              <h5 class='text-white text-center'>{{ratingItem.score|floatformat:"0" }}/10 ({{ratingItem.score|rating_verbose}})</h5>
          </div>
        </div>
      {% endfor %}
    {% endif %}
    {% endfor %}
  </div>
{% endblock main %}

mySite/applications/rating/templates/rating/ratingSystem.html
{% extends 'base.html' %}


{% block title %}Рейтинговая система{% endblock title %}


{% block navigate %}{% endblock navigate %}


{% block main %}
  <div class="container mt-2">
  <ul class="nav mb-2 fs-3">
    <li>
      <a href="#" class="nav-link mx-1 text-white hovered">← Назад</a>
    </li>
  </ul>
    <h3 class='text-white'>Введение:</h3>
    <p style='text-align:justify; font-size: 18px;' class="text-muted">Данная страница предназначена для того, чтобы объяснить рядовому пользователю то, какой системой оценивания я пользуюсь для просмотренных/прочтенных/проигранных произведений. Непосресредственно сама система не представляет из себя ничего интересного или уникального, но данное пояснение все же необходимо для полного понимания. Люди бывают разные, с разными подходами к оцениванию, и если они приходят ко мне на сайт, то я обязан разъяснить для них свой.</p>
    <h3 class='text-white'>Критерии:</h3>
    <p style='text-align:justify; font-size: 18px;' class="text-muted">Непосредственно сами критерии представляют собой мои маняфантазии. Произведения я стараюсь оценивать с позиции своих вкусов одновременно с попыткой в объективное оценивание, разделяя эти понятия, отчего для каждой оценки имеется свой нефиксированный набор критериев. В случае с моими вкусами тут все просто: критерий один - мое общее впечатление от произведения, в котором я описываю те аспекты, которые понравились лично мне. С объективным оцениванием все сложнее. Здесь для каждого типа произведения, будь то мультфильм, просто фильм, сериал, книга, игра, имеется свой набор уникальных критериев: проблематично оценивать раскадровку у игры или геймдизайн у книги. Иногда некоторые критерии могут быть пропущены по самым разным причинам.</p>
    <h3 class="text-white">Из чего складывается общая оценка:</h3>
    <p style='text-align:justify; font-size: 18px;' class="text-muted">Пока что только из среднего значения всех оценок одного типа (объективные или субъективные). Достаточно просто, но я пока разбираюсь с SQL, поэтому сложные агрегирующие запросы делать не умею. Дополнением к итоговой оценке идет сдвиг по принципу академической щедрости. В данный принцип я вкладываю немного другое значение, чем оно имеет (справка: "академическая щедрость" - принцип, при котором дебатирующие стороны при интерпретации слов оппонента не пытаются их негативно интерпретировать, дают ему фору для объяснения, не прибегают к софистике, додумывают слова для наиболее выигрышной позиции оппонента. Обобщу: ведут себя благосклонно по отношении к собеседнику ), а именно добавление к итоговой оценке определенное количество баллов в силу того, что либо само произведение, либо индустрия, в которой оно было произведено (кинопроизводство отдельной страны и т.д.) перспективно или очень интересно для меня. <b>Данный принцип распространяется только на мое субъективное мнение.</b></p>
    <h3 class="text-white">У меня лапки:</h3>
    <p style='text-align:justify; font-size: 18px;' class="text-muted">Тут мне стоит сказать еще раз, что я не претендую на истину в последней инстанции. Я могу ошибаться, а могу нарочно что-то недорассказать, чтобы моя позиция смотрелась гораздо выигрышнее. Полностью доверять моим оценкам себе дороже. Думайте своей головой.</p>
    <h3 class="text-white">Что бы я улучшил в своей системе:</h3>
    <p style='text-align:justify; font-size: 18px;' class="text-muted">На самом деле, пока что кроме какой-нибудь системы весов для оценок (вес - некоторое число, показывающая важность оценки, за которой оно закреплено. Пример: устанавливая вес атрибута сюжет в 0.5 я говорю о том, что если я поставлю сюжету произведения оценку 10, тогда к итоговой оценке прибавится 5 баллов (10*0.5=5)) мне добавить нечего, да и усложнять систему плохо со всех сторон.</p>
    <p style='text-align:justify; font-size: 18px;' class="text-muted">З.ы. эта часть текста может быть удалена, если я все-таки добавлю те вещи, о которых говорилось выше.</p>
  </div>
{% endblock main %}