mySite/applications/microblog/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import PostDelete, PostDetail, PostList, PostsByTagsList


app_name = "microblog"

urlpatterns = [
    path("", PostList.as_view(), name="list"),
    path("post/<slug:slug>", PostDetail.as_view(), name="detail"),
    path("by-tag=<str:name>", PostsByTagsList.as_view(), name="tags"),
    path("post/<slug:slug>/delete", PostDelete.as_view(), name="delete"),
]

mySite/mySite/urls.py
import debug_toolbar

from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),

    path('', RedirectView.as_view(pattern_name='microblog:list')),
    path('microblog/', include('microblog.urls', namespace='microblog')),
    path('about-me/', include('resume.urls')),
    path('myList/', include('myList.urls', namespace='myList')),
    path('rating/', include('rating.urls', namespace='rating')),
    path('api/v1/', include('api.urls', namespace='api')),
]


if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mySite/applications/microblog/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class Post(models.Model):
    """Класс модели постов моего микроблога.

    Автора нет, так как им в 100% случаев буду только я.
    """

    title = models.CharField(max_length=255, unique=True, verbose_name="Заголовок")
    text = models.TextField(verbose_name="Текст")
    slug = models.SlugField(null=True, max_length=300)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата написания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")
    published_at = models.DateTimeField(blank=True, null=True, verbose_name="Дата публикации")
    is_published = models.BooleanField(default=False, verbose_name="Опубликовано?")
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse("microblog/postDetail", kwargs={"slug": self.slug})

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["updated_at"]

mySite/applications/microblog/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms
from taggit.forms import TagWidget

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "text", "tags", "is_published")
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control text-white bg-dark"}),
            "text": CKEditorUploadingWidget(attrs={"class": "form-control text-white bg-dark"}),
            "tags": TagWidget(attrs={"class": "form-control text-white bg-dark"}),
            "is_published": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }

mySite/applications/microblog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render
from django.views.generic import ListView, DeleteView, DetailView

from .models import Post


class PostList(ListView):
    template_name = "microblog/postList.html"
    model = Post
    context_object_name = "posts"
    paginate_by = 12

    def post(self, request: HttpRequest) -> HttpResponse:
        """Переопределенный метод класса ListView для обработки поиска по
        названию поста и тэгам.
        """
        search = request.POST.get("search")
        query = Post.objects.filter(Q(title__icontains=search) | Q(tags__name=search))
        return render(request, self.template_name, context={"posts": query})


class PostsByTagsList(PostList):
    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs["name"])


class PostDetail(DetailView):
    model = Post
    template_name = "microblog/postDetail.html"
    context_object_name = "post"
    slug_url_kwarg = "slug"


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = "microblog/postDelete.html"
    context_object_name = "post"
    success_url = "/microblog/"

mySite/applications/microblog/templates/microblog/microblogBase.html
{% extends 'base.html' %}


{% block navigate %}
  {{ block.super }}
  {% block search %}
    <div class="container">{% include 'microblog/inc/_searchbar.html' %}</div>
  {% endblock search %}
{% endblock navigate %}

mySite/applications/microblog/templates/microblog/postDelete.html
{% extends 'base.html' %}


{% block navigate %}{% endblock navigate %}


{% block main %}
<div class="container mt-2">
<div class="form-group mx-auto">
  <h2 class="text-center text-white mt-3">
    Вы собираетесь <span class="text-danger">удалить</span> пост "<i>{{ post}}</i>"
  </h2>
  <p class="text-center">Вы уверены, что хотите это сделать?</p>
  <div class="form-group">
    <form
      method="post"
      class="d-flex flex-column align-items-center justify-content-center"
      >
      {% csrf_token %}
      <div class="row">
        <div class="col">
          <a href="{% url 'microblog:detail' slug=post.slug %}" class="nav-link text-white fs-4 hovered">Назад</a>
        </div>
        <div class="col">
          <button type="submit" class="btn btn-danger fs-4">Удалить</button>
        </div>
      </div>
    </form>
  </div>
</div>
    </div>
{% endblock main %}

mySite/applications/microblog/templates/microblog/postDetail.html
{% extends 'base.html' %}


{% block navigate %}{% endblock navigate %}


{% block main %}
<div class="container mt-2">

    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center fs-3 border">
        <li>
            <a href="{% url 'microblog:list' %}" class="nav-link mx-1 text-white hovered">Назад</a>
        </li>
        {% if user.is_superuser %}
        <li>
            <a href="{% url 'microblog:delete' slug=post.slug %}" class="nav-link mx-1 text-white hovered">Удалить</a>
        </li>
        <li>
            <a href="{% url 'admin:microblog_post_change' post.pk %}" class="nav-link mx-1 text-white hovered">Обновить</a>
        </li>
        <li>
            <a href="{% url 'admin:index' %}" class="nav-link mx-1 text-white hovered">Админка</a>
        </li>
        {% endif %}
    </ul>

    <div class="row">
        <article>
            <header class="mb-4 mt-2">
                <h1 class="fw-bolder mb-1 text-white">{{post.title}}</h1>

                {% if post.is_published %}
                    <div class="text-muted fst-italic mb-2 text-white">Опубликовано {{post.published_at}} мной лично.</div>
                {% else %}
                    <div class="text-muted fst-italic mb-2 text-white">Ещё не опубликовано.</div>
                {% endif %}

                {% for tag in post.tags.all %}
                    <a class="badge bg-secondary text-decoration-none link-light" href="{% url 'microblog:tags' name=tag.name %}">{{tag.name}}</a>
                {% endfor %}

            </header>
            <section class="text-white">
                <p class='text-white'>{{post.text|safe}}</p>
            </section>
        </article>
    </div>
</div>
{% endblock main %}

mySite/applications/microblog/templates/microblog/postList.html
{% extends 'microblog/microblogBase.html' %}

{% block navigate %}
{{ block.super }}
{% endblock navigate %}


{% block main %}
<div class="container mt-1">
  {% include 'microblog/inc/_tagsList.html' %}
<div class="mt-2"></div>
{% for post in posts %}
{% if request.user.is_staff or request.user.is_superuser or post.is_published %}
<div class="card text-white bg-dark border border-white">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <p class="nav-link active">Пост</p>
      </li>
      <li class="nav-item">
        <h2 class="navbar-brand mx-3">{{post.title|truncatewords:50}}</h2>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <p class="card-text">{{post.text|truncatewords:50|safe}}</p>
    <a href="{% url 'microblog:detail' slug=post.slug %}" class="btn btn-danger btn-custom">Подробнее</a>
  </div>
</div>
{% endif %}
{% empty %}
<p class="fs-1 text-white text-center">Видимо, я пока что ничего не написал (или ещё не опубликовал). Вернитесь сюда позже.</p>
{% endfor %}
</div>
{% endblock main %}